.\" Man Page for WMWAVE
.\" groff -man -Tascii wmwave.1
.\"
.TH WMWAVE 1 "AUGUST 1999" Linux "User Manuals"
.SH NAME
wmwave
.SH SYNOPSIS
.B wmwave
[\-c command]
.SH DESCRIPTION
.B wmwave
displays, as a WindowMaker dockapp, statistical information for 
wireless ethernet.  
.SH OPTIONS

.TP
.I \-r time
Sets the update interval (in milliseconds), default: 100

.I \-display display
This option specifies the X server to contact; see X(1).


.SH BUGS
Please report any bugs you may find to:
.TP
.B dockapps@schuermann.org
.SH AUTHOR
Carsten Schuermann <carsten@schuermann.org>
.SH Homepage
http://wmwave.sourceforge.net
